spring:
  application:
    name: service-support
  profiles:
    active: server2
  #  application-server1.yml配置文件如下：
server:
  port: 8763
eureka:
  instance:
    hostname: server2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/