spring:
  application:
    name: service-support
  profiles:
    active: server1
  #  application-server1.yml配置文件如下：
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jayking_works
    username: root
    password: 123456
server:
  port: 8762
eureka:
  instance:
    # 配置主机名
    hostname: service-support
    # 显示 ip 地址，代替显示主机名
    prefer-ip-address: true
    # 所注册服务实例名称的显示形式
    instance-id: ${eureka.instance.hostname}:${server.port}
    # 每隔 3 秒发一次心跳包
    lease-renewal-interval-in-seconds: 3
    # 如果 15 秒没有发送心跳包，就让 eureka 把自己从服务列表中移除
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    # 是否需要从 eureka 中抓取路径
    fetch-registry: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
  config: classpath:log4j2.xml
