server:
  port: 8100

eureka:
  instance:
    # 配置主机名
    hostname: consumer-service
    # 显示 ip 地址，代替显示主机名
    prefer-ip-address: true
    # 所注册服务实例名称的显示形式
    instance-id: ${eureka.instance.hostname}:${server.port}
    # 每隔 3 秒发一次心跳包
    lease-renewal-interval-in-seconds: 3
    # 如果 15 秒没有发送心跳包，就让 eureka 把自己从服务列表中移除
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      # 将当前 springboot 服务注册到 eureka 中
      defaultZone: http://localhost:8761/eureka
    # 是否将自己的路径注册到 eureka 上
    register-with-eureka: true
    # 是否需要从 eureka 中抓取路径
    fetch-registry: true

# consumer 使用的 application 名称
spring:
  application:
    name: consumer-App

# 这里可以设置 feign 客户端连接和获取接口数据的超时时间
feign:
  client:
    config:
      # 通过 default 可以设置 feign 默认超时时间
      default:
        # 连接超时时间（毫秒）
        connect-timeout: 1000
        # 等待业务处理返回结果的超时时间（毫秒）
        read-timeout: 1000
      # 这里可以针对具体的【服务提供者】应用名称下的所有接口，设置超时时间
#      PROVIDER-APP:
#        ConnectTimeout: 1000
#        ReadTimeout: 3000